/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppSubjectsIndexRouteImport } from './routes/_app.subjects.index'
import { Route as AppSubjectsSubjectIdIndexRouteImport } from './routes/_app.subjects.$subjectId.index'
import { Route as AppSubjectsSubjectIdChatRouteImport } from './routes/_app.subjects.$subjectId.chat'
import { Route as AppQuizzesQuizIdTakeRouteImport } from './routes/_app.quizzes.$quizId.take'
import { Route as AppQuizzesQuizIdResultsRouteImport } from './routes/_app.quizzes.$quizId.results'
import { Route as AppSubjectsSubjectIdQuizzesIndexRouteImport } from './routes/_app.subjects.$subjectId.quizzes.index'
import { Route as AppSubjectsSubjectIdDocumentsIndexRouteImport } from './routes/_app.subjects.$subjectId.documents.index'
import { Route as AppSubjectsSubjectIdDocumentsDocIdRouteImport } from './routes/_app.subjects.$subjectId.documents.$docId'
import { Route as AppSubjectsSubjectIdConversationsConversationIdRouteImport } from './routes/_app.subjects.$subjectId.conversations.$conversationId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsIndexRoute = AppSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsSubjectIdIndexRoute =
  AppSubjectsSubjectIdIndexRouteImport.update({
    id: '/subjects/$subjectId/',
    path: '/subjects/$subjectId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppSubjectsSubjectIdChatRoute =
  AppSubjectsSubjectIdChatRouteImport.update({
    id: '/subjects/$subjectId/chat',
    path: '/subjects/$subjectId/chat',
    getParentRoute: () => AppRoute,
  } as any)
const AppQuizzesQuizIdTakeRoute = AppQuizzesQuizIdTakeRouteImport.update({
  id: '/quizzes/$quizId/take',
  path: '/quizzes/$quizId/take',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesQuizIdResultsRoute = AppQuizzesQuizIdResultsRouteImport.update({
  id: '/quizzes/$quizId/results',
  path: '/quizzes/$quizId/results',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsSubjectIdQuizzesIndexRoute =
  AppSubjectsSubjectIdQuizzesIndexRouteImport.update({
    id: '/subjects/$subjectId/quizzes/',
    path: '/subjects/$subjectId/quizzes/',
    getParentRoute: () => AppRoute,
  } as any)
const AppSubjectsSubjectIdDocumentsIndexRoute =
  AppSubjectsSubjectIdDocumentsIndexRouteImport.update({
    id: '/subjects/$subjectId/documents/',
    path: '/subjects/$subjectId/documents/',
    getParentRoute: () => AppRoute,
  } as any)
const AppSubjectsSubjectIdDocumentsDocIdRoute =
  AppSubjectsSubjectIdDocumentsDocIdRouteImport.update({
    id: '/subjects/$subjectId/documents/$docId',
    path: '/subjects/$subjectId/documents/$docId',
    getParentRoute: () => AppRoute,
  } as any)
const AppSubjectsSubjectIdConversationsConversationIdRoute =
  AppSubjectsSubjectIdConversationsConversationIdRouteImport.update({
    id: '/subjects/$subjectId/conversations/$conversationId',
    path: '/subjects/$subjectId/conversations/$conversationId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AppAccountRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/subjects/': typeof AppSubjectsIndexRoute
  '/quizzes/$quizId/results': typeof AppQuizzesQuizIdResultsRoute
  '/quizzes/$quizId/take': typeof AppQuizzesQuizIdTakeRoute
  '/subjects/$subjectId/chat': typeof AppSubjectsSubjectIdChatRoute
  '/subjects/$subjectId/': typeof AppSubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/conversations/$conversationId': typeof AppSubjectsSubjectIdConversationsConversationIdRoute
  '/subjects/$subjectId/documents/$docId': typeof AppSubjectsSubjectIdDocumentsDocIdRoute
  '/subjects/$subjectId/documents/': typeof AppSubjectsSubjectIdDocumentsIndexRoute
  '/subjects/$subjectId/quizzes/': typeof AppSubjectsSubjectIdQuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AppAccountRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/subjects': typeof AppSubjectsIndexRoute
  '/quizzes/$quizId/results': typeof AppQuizzesQuizIdResultsRoute
  '/quizzes/$quizId/take': typeof AppQuizzesQuizIdTakeRoute
  '/subjects/$subjectId/chat': typeof AppSubjectsSubjectIdChatRoute
  '/subjects/$subjectId': typeof AppSubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/conversations/$conversationId': typeof AppSubjectsSubjectIdConversationsConversationIdRoute
  '/subjects/$subjectId/documents/$docId': typeof AppSubjectsSubjectIdDocumentsDocIdRoute
  '/subjects/$subjectId/documents': typeof AppSubjectsSubjectIdDocumentsIndexRoute
  '/subjects/$subjectId/quizzes': typeof AppSubjectsSubjectIdQuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/account': typeof AppAccountRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/subjects/': typeof AppSubjectsIndexRoute
  '/_app/quizzes/$quizId/results': typeof AppQuizzesQuizIdResultsRoute
  '/_app/quizzes/$quizId/take': typeof AppQuizzesQuizIdTakeRoute
  '/_app/subjects/$subjectId/chat': typeof AppSubjectsSubjectIdChatRoute
  '/_app/subjects/$subjectId/': typeof AppSubjectsSubjectIdIndexRoute
  '/_app/subjects/$subjectId/conversations/$conversationId': typeof AppSubjectsSubjectIdConversationsConversationIdRoute
  '/_app/subjects/$subjectId/documents/$docId': typeof AppSubjectsSubjectIdDocumentsDocIdRoute
  '/_app/subjects/$subjectId/documents/': typeof AppSubjectsSubjectIdDocumentsIndexRoute
  '/_app/subjects/$subjectId/quizzes/': typeof AppSubjectsSubjectIdQuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/register'
    | '/subjects/'
    | '/quizzes/$quizId/results'
    | '/quizzes/$quizId/take'
    | '/subjects/$subjectId/chat'
    | '/subjects/$subjectId/'
    | '/subjects/$subjectId/conversations/$conversationId'
    | '/subjects/$subjectId/documents/$docId'
    | '/subjects/$subjectId/documents/'
    | '/subjects/$subjectId/quizzes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/register'
    | '/subjects'
    | '/quizzes/$quizId/results'
    | '/quizzes/$quizId/take'
    | '/subjects/$subjectId/chat'
    | '/subjects/$subjectId'
    | '/subjects/$subjectId/conversations/$conversationId'
    | '/subjects/$subjectId/documents/$docId'
    | '/subjects/$subjectId/documents'
    | '/subjects/$subjectId/quizzes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/account'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/subjects/'
    | '/_app/quizzes/$quizId/results'
    | '/_app/quizzes/$quizId/take'
    | '/_app/subjects/$subjectId/chat'
    | '/_app/subjects/$subjectId/'
    | '/_app/subjects/$subjectId/conversations/$conversationId'
    | '/_app/subjects/$subjectId/documents/$docId'
    | '/_app/subjects/$subjectId/documents/'
    | '/_app/subjects/$subjectId/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects/': {
      id: '/_app/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof AppSubjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects/$subjectId/': {
      id: '/_app/subjects/$subjectId/'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId/'
      preLoaderRoute: typeof AppSubjectsSubjectIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects/$subjectId/chat': {
      id: '/_app/subjects/$subjectId/chat'
      path: '/subjects/$subjectId/chat'
      fullPath: '/subjects/$subjectId/chat'
      preLoaderRoute: typeof AppSubjectsSubjectIdChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quizzes/$quizId/take': {
      id: '/_app/quizzes/$quizId/take'
      path: '/quizzes/$quizId/take'
      fullPath: '/quizzes/$quizId/take'
      preLoaderRoute: typeof AppQuizzesQuizIdTakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quizzes/$quizId/results': {
      id: '/_app/quizzes/$quizId/results'
      path: '/quizzes/$quizId/results'
      fullPath: '/quizzes/$quizId/results'
      preLoaderRoute: typeof AppQuizzesQuizIdResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects/$subjectId/quizzes/': {
      id: '/_app/subjects/$subjectId/quizzes/'
      path: '/subjects/$subjectId/quizzes'
      fullPath: '/subjects/$subjectId/quizzes/'
      preLoaderRoute: typeof AppSubjectsSubjectIdQuizzesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects/$subjectId/documents/': {
      id: '/_app/subjects/$subjectId/documents/'
      path: '/subjects/$subjectId/documents'
      fullPath: '/subjects/$subjectId/documents/'
      preLoaderRoute: typeof AppSubjectsSubjectIdDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects/$subjectId/documents/$docId': {
      id: '/_app/subjects/$subjectId/documents/$docId'
      path: '/subjects/$subjectId/documents/$docId'
      fullPath: '/subjects/$subjectId/documents/$docId'
      preLoaderRoute: typeof AppSubjectsSubjectIdDocumentsDocIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects/$subjectId/conversations/$conversationId': {
      id: '/_app/subjects/$subjectId/conversations/$conversationId'
      path: '/subjects/$subjectId/conversations/$conversationId'
      fullPath: '/subjects/$subjectId/conversations/$conversationId'
      preLoaderRoute: typeof AppSubjectsSubjectIdConversationsConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppSubjectsIndexRoute: typeof AppSubjectsIndexRoute
  AppQuizzesQuizIdResultsRoute: typeof AppQuizzesQuizIdResultsRoute
  AppQuizzesQuizIdTakeRoute: typeof AppQuizzesQuizIdTakeRoute
  AppSubjectsSubjectIdChatRoute: typeof AppSubjectsSubjectIdChatRoute
  AppSubjectsSubjectIdIndexRoute: typeof AppSubjectsSubjectIdIndexRoute
  AppSubjectsSubjectIdConversationsConversationIdRoute: typeof AppSubjectsSubjectIdConversationsConversationIdRoute
  AppSubjectsSubjectIdDocumentsDocIdRoute: typeof AppSubjectsSubjectIdDocumentsDocIdRoute
  AppSubjectsSubjectIdDocumentsIndexRoute: typeof AppSubjectsSubjectIdDocumentsIndexRoute
  AppSubjectsSubjectIdQuizzesIndexRoute: typeof AppSubjectsSubjectIdQuizzesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppSubjectsIndexRoute: AppSubjectsIndexRoute,
  AppQuizzesQuizIdResultsRoute: AppQuizzesQuizIdResultsRoute,
  AppQuizzesQuizIdTakeRoute: AppQuizzesQuizIdTakeRoute,
  AppSubjectsSubjectIdChatRoute: AppSubjectsSubjectIdChatRoute,
  AppSubjectsSubjectIdIndexRoute: AppSubjectsSubjectIdIndexRoute,
  AppSubjectsSubjectIdConversationsConversationIdRoute:
    AppSubjectsSubjectIdConversationsConversationIdRoute,
  AppSubjectsSubjectIdDocumentsDocIdRoute:
    AppSubjectsSubjectIdDocumentsDocIdRoute,
  AppSubjectsSubjectIdDocumentsIndexRoute:
    AppSubjectsSubjectIdDocumentsIndexRoute,
  AppSubjectsSubjectIdQuizzesIndexRoute: AppSubjectsSubjectIdQuizzesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
